// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/twinklehawk/ddns-updater-go/internal/ipprovider (interfaces: CurrentIpProvider)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_ipprovider.go -package=mocks . CurrentIpProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCurrentIpProvider is a mock of CurrentIpProvider interface.
type MockCurrentIpProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCurrentIpProviderMockRecorder
	isgomock struct{}
}

// MockCurrentIpProviderMockRecorder is the mock recorder for MockCurrentIpProvider.
type MockCurrentIpProviderMockRecorder struct {
	mock *MockCurrentIpProvider
}

// NewMockCurrentIpProvider creates a new mock instance.
func NewMockCurrentIpProvider(ctrl *gomock.Controller) *MockCurrentIpProvider {
	mock := &MockCurrentIpProvider{ctrl: ctrl}
	mock.recorder = &MockCurrentIpProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrentIpProvider) EXPECT() *MockCurrentIpProviderMockRecorder {
	return m.recorder
}

// GetCurrentIp mocks base method.
func (m *MockCurrentIpProvider) GetCurrentIp(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentIp", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentIp indicates an expected call of GetCurrentIp.
func (mr *MockCurrentIpProviderMockRecorder) GetCurrentIp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentIp", reflect.TypeOf((*MockCurrentIpProvider)(nil).GetCurrentIp), ctx)
}
