// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/twinklehawk/ddns-updater-go/internal/ddnsservice (interfaces: PorkbunClient)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_porkbun.go -package=mocks . PorkbunClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	porkbun "github.com/greatliontech/porkbun-go"
	gomock "go.uber.org/mock/gomock"
)

// MockPorkbunClient is a mock of PorkbunClient interface.
type MockPorkbunClient struct {
	ctrl     *gomock.Controller
	recorder *MockPorkbunClientMockRecorder
	isgomock struct{}
}

// MockPorkbunClientMockRecorder is the mock recorder for MockPorkbunClient.
type MockPorkbunClientMockRecorder struct {
	mock *MockPorkbunClient
}

// NewMockPorkbunClient creates a new mock instance.
func NewMockPorkbunClient(ctrl *gomock.Controller) *MockPorkbunClient {
	mock := &MockPorkbunClient{ctrl: ctrl}
	mock.recorder = &MockPorkbunClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPorkbunClient) EXPECT() *MockPorkbunClientMockRecorder {
	return m.recorder
}

// EditDNSRecordByNameType mocks base method.
func (m *MockPorkbunClient) EditDNSRecordByNameType(ctx context.Context, domain string, recordType porkbun.RecordType, subdomain string, record *porkbun.EditDNSRecordByNameTypeRequest) (*porkbun.EditDNSRecordByNameTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditDNSRecordByNameType", ctx, domain, recordType, subdomain, record)
	ret0, _ := ret[0].(*porkbun.EditDNSRecordByNameTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditDNSRecordByNameType indicates an expected call of EditDNSRecordByNameType.
func (mr *MockPorkbunClientMockRecorder) EditDNSRecordByNameType(ctx, domain, recordType, subdomain, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditDNSRecordByNameType", reflect.TypeOf((*MockPorkbunClient)(nil).EditDNSRecordByNameType), ctx, domain, recordType, subdomain, record)
}

// RetrieveDNSRecordsByNameType mocks base method.
func (m *MockPorkbunClient) RetrieveDNSRecordsByNameType(ctx context.Context, domain string, recordType porkbun.RecordType, subdomain string) (*porkbun.RetrieveDNSRecordsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveDNSRecordsByNameType", ctx, domain, recordType, subdomain)
	ret0, _ := ret[0].(*porkbun.RetrieveDNSRecordsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveDNSRecordsByNameType indicates an expected call of RetrieveDNSRecordsByNameType.
func (mr *MockPorkbunClientMockRecorder) RetrieveDNSRecordsByNameType(ctx, domain, recordType, subdomain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveDNSRecordsByNameType", reflect.TypeOf((*MockPorkbunClient)(nil).RetrieveDNSRecordsByNameType), ctx, domain, recordType, subdomain)
}
