// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/twinklehawk/ddns-updater-go/internal/ddnsservice (interfaces: DdnsService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_ddnsservice.go -package=mocks . DdnsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDdnsService is a mock of DdnsService interface.
type MockDdnsService struct {
	ctrl     *gomock.Controller
	recorder *MockDdnsServiceMockRecorder
	isgomock struct{}
}

// MockDdnsServiceMockRecorder is the mock recorder for MockDdnsService.
type MockDdnsServiceMockRecorder struct {
	mock *MockDdnsService
}

// NewMockDdnsService creates a new mock instance.
func NewMockDdnsService(ctrl *gomock.Controller) *MockDdnsService {
	mock := &MockDdnsService{ctrl: ctrl}
	mock.recorder = &MockDdnsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDdnsService) EXPECT() *MockDdnsServiceMockRecorder {
	return m.recorder
}

// GetHostIpv4 mocks base method.
func (m *MockDdnsService) GetHostIpv4(ctx context.Context, subdomain, domain string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostIpv4", ctx, subdomain, domain)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostIpv4 indicates an expected call of GetHostIpv4.
func (mr *MockDdnsServiceMockRecorder) GetHostIpv4(ctx, subdomain, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostIpv4", reflect.TypeOf((*MockDdnsService)(nil).GetHostIpv4), ctx, subdomain, domain)
}

// UpdateHostIpv4 mocks base method.
func (m *MockDdnsService) UpdateHostIpv4(ctx context.Context, subdomain, domain, ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHostIpv4", ctx, subdomain, domain, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHostIpv4 indicates an expected call of UpdateHostIpv4.
func (mr *MockDdnsServiceMockRecorder) UpdateHostIpv4(ctx, subdomain, domain, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHostIpv4", reflect.TypeOf((*MockDdnsService)(nil).UpdateHostIpv4), ctx, subdomain, domain, ip)
}
